spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kb_star_banking"
    username: "root"
    password: "0818"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: false
